http {
    include mime.types;
    types {
        application/javascript js mjs;
    }
    default_type application/octet-stream;
    
    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}