name: Deploy to AWS ECS

on:
  push:
    branches:
      - develop  # Run this workflow on every push to the develop branch
      - fix/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ${{vars.AWS_REGION}}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and tag Docker image
        env:
          REPO_URI: ${{vars.REPO_URI}}
        run: |
          cd ./jkirisa-web-app
          docker build -t $REPO_URI:latest .
          docker tag $REPO_URI:latest $REPO_URI:${{ github.sha }}

      - name: Push to Amazon ECR
        env:
          REPO_URI: ${{vars.REPO_URI}}
        run: |
          docker push $REPO_URI:latest
          docker push $REPO_URI:${{ github.sha }}

      - name: Update ECS task definition
        env:
          AWS_REGION: ${{vars.AWS_REGION}}
          REPO_URI: ${{vars.REPO_URI}}
          TASK_FAMILY: ${{vars.ECS_TASK_FAMILY}}
        run: |
          TASK_DEF_JSON=$(aws ecs describe-task-definition --task-definition $TASK_FAMILY --region $AWS_REGION)
          NEW_TASK_DEF_JSON=$(echo $TASK_DEF_JSON | jq --arg IMAGE_URI "$REPO_URI:${{ github.sha }}" '.taskDefinition | .containerDefinitions[0].image = $IMAGE_URI | { family: .family, networkMode: .networkMode, containerDefinitions: .containerDefinitions, requiresCompatibilities: .requiresCompatibilities, cpu: .cpu, memory: .memory }')
          echo "$NEW_TASK_DEF_JSON" > new-task-def.json
          aws ecs register-task-definition --cli-input-json file://new-task-def.json --region $AWS_REGION --execution-role-arn arn:aws:iam::033557458086:role/ecsTaskExecutionRole

      - name: Deploy to Amazon ECS
        env:
          AWS_REGION: ${{vars.AWS_REGION}}
          CLUSTER: ${{vars.ECS_CLUSTER_NAME}}
          SERVICE: ${{vars.ECS_SERVICE_NAME}}
          IMAGE_URI: ${{vars.REPO_URI}}:${{ github.sha }}
          TASK_FAMILY: ${{vars.ECS_TASK_FAMILY}}
        run: |
          aws ecs update-service --cluster $CLUSTER --service $SERVICE --force-new-deployment --task-definition $TASK_FAMILY:latest --region $AWS_REGION